# docker-compose.yml (PRODUCTION BASE)
services:
  postgres:
    image: postgis/postgis:14-3.4
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - '3001:3001'
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
    driver: local
