# docker-compose.override.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    
    command: npm run dev:api

    volumes:
      - .:/data/app
      - /data/app/node_modules