# docker-compose.yml (PRODUCTION BASE)
services:
  postgres:
    image: postgis/postgis:14-3.4 # Use the official PostGIS image
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Standard Postgres data path

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build:
      # Tell Docker to build the image using the api-gateway's context
      context: ./apps/api-gateway
      dockerfile: ../../Dockerfile # Point to the root Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    # The CMD from the Dockerfile will be used (pnpm run start:api)
    depends_on:
      - postgres
      - redis

volumes:
    pgdata:
      driver: local
