# docker-compose.yml
services:
  postgres:
    container_name: pgdb
    image: postgres:14-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgresql/data

  redis:
    image: redis:7-alpine

  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: nodemon dist/index.js
    depends_on:
      - postgres
      - redis
volumes:
    pgdata:
      driver: local
