# Dockerfile.dev (FOR DEVELOPMENT ONLY)

FROM node:20
WORKDIR /data/app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/ /data/app/apps/
COPY packages/ /data/app/packages/

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev:api"]

